<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="GUO-PC" name="login" tests="4" failures="1" timestamp="3 Dec 2017 13:50:53 GMT" time="87.712" errors="0">
  <testcase name="loginDemo" time="18.316" classname="com.gorky.appiumdemo.testcases.login.LoginPage_001_LoginCase_Test"/>
  <testcase name="loginDemo" time="21.718" classname="com.gorky.appiumdemo.testcases.login.LoginPage_001_LoginCase_Test"/>
  <testcase name="loginDemo" time="20.344" classname="com.gorky.appiumdemo.testcases.login.LoginPage_001_LoginCase_Test"/>
  <testcase name="loginDemo" time="68.281" classname="com.gorky.appiumdemo.testcases.login.LoginPage_001_LoginCase_Test">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at com.gorky.appiumdemo.utils.ExcelDataProvider.hasNext(ExcelDataProvider.java:84)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- loginDemo -->
</testsuite> <!-- login -->
